name: recipe
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_analytics: ^10.1.0
  cloud_firestore: ^4.3.1

  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1

  google_sign_in: ^5.3.3

  tinycolor2: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true