// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYf6pcvoY7gRAWa6O7qCvngyiDqo_cxf0',
    appId: '1:189236704531:web:371153129954cbbac696e6',
    messagingSenderId: '189236704531',
    projectId: 'recipe-e',
    authDomain: 'recipe-e.firebaseapp.com',
    storageBucket: 'recipe-e.appspot.com',
    measurementId: 'G-X8NGWNHLDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4bp09nLiZFShP17wvsrcHVE2gpceiDoI',
    appId: '1:189236704531:android:213d7d0ae8804a27c696e6',
    messagingSenderId: '189236704531',
    projectId: 'recipe-e',
    storageBucket: 'recipe-e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPKx-9bnIllIbvB65nfDIRRK026MGJ1bs',
    appId: '1:189236704531:ios:33c027cc79dc6e8bc696e6',
    messagingSenderId: '189236704531',
    projectId: 'recipe-e',
    storageBucket: 'recipe-e.appspot.com',
    iosClientId: '189236704531-dikh9mn9g2mnc5qlam6oeb0g1qkds725.apps.googleusercontent.com',
    iosBundleId: 'easecore.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPKx-9bnIllIbvB65nfDIRRK026MGJ1bs',
    appId: '1:189236704531:ios:33c027cc79dc6e8bc696e6',
    messagingSenderId: '189236704531',
    projectId: 'recipe-e',
    storageBucket: 'recipe-e.appspot.com',
    iosClientId: '189236704531-dikh9mn9g2mnc5qlam6oeb0g1qkds725.apps.googleusercontent.com',
    iosBundleId: 'easecore.recipe',
  );
}
